### ISSUE TITLE
NFS lock manager should be removed when mapr-nfsserver is installed

### ISSUE THREAD

**Issue by andypern** [vicenteg/mapr-ansible-roles#33]
The linux NLM/NFS lock manager has a tendency to get in the way when it is running on a host which is also running mapr-nfsserver .  Its particularly cumbersom if you are trying to connect a Windows NFS client, which will just throw 'error 53' whenever you try to mount.

You can verify if it is running via:

rpcinfo -p | grep lock

Which will show you:

  100021    1   udp  55745  nlockmgr
    100021    3   udp  55745  nlockmgr
    100021    4   udp  55745  nlockmgr
    100021    1   tcp  34210  nlockmgr
    100021    3   tcp  34210  nlockmgr
    100021    4   tcp  34210  nlockmgr

I'm not 100% sure which RPM this relates to.  There is a service in /etc/init.d/ named 'nfslock' => but I've tried stopping the service to no avail. The only way I got nlockmgr to stop running was by running the following commands..which probbaly won't survive a reboot:

rpcinfo -d 100021 1
rpcinfo -d 100021 2
rpcinfo -d 100021 3
rpcinfo -d 100021 4
rpcinfo -d 100021 5

**Comment by vicenteg** [comment]
fixed in 85defa62a242568cb49284a281a0989b8d47461d
